{/* <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    By starting with 1 and 2 the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.</p> */}

function problem02(F1,F2){
    list = []
    if(F2 %2 ==0){
        list.push(F2)
    }
    for(i=0; i<100; i++){
        F = F1 +F2;
        F1 = F2;
        F2 = F;
        if(F>=4000000){
            break;
        }
        if(F%2==0){
            list.push(F);
        }
        
    }
    result = addArray(list);
    return result
}

function addArray(list){
    arr = 0
    for(i=0; i<list.length; i++){
        arr = arr + list[i]
    }
    return arr

}

console.log(problem02(1,2))